agentlang-ai/agentlang-clj

- src/fractl/lang.cljc
> for empty pre/post dataflows, return the instance

- bin/fractl
- src/fractl/lang/tools/repl.clj
- src/fractl/lang/tools/replcmds.clj
1. clone/install fractl-lein-template.
2. default to current-component in repl.
3. fn to switch components in repl.
> clone/install fractl-lein-template.

- src/fractl/lang/rbac.cljc
- src/fractl/store/jdbc_internal.clj
- src/fractl/util.cljc
- test/fractl/test/features02.cljc
- test/fractl/test/fixes01.cljc
- test/fractl/test/fixes02.cljc
- test/fractl/test/util.cljc
> Issue 1135 - report unique-id conflicts in the store as error

- src/fractl/lang.cljc
- test/fractl/test/features02.cljc
E:g.
```
(relationship :BelongsTo
{:meta {:between [:BlogPost :Category]
:one-one true}})
```
> Relationship properties can be specified in :meta

- src/fractl/global_state.cljc
- src/fractl/store/util.cljc
> support schema-version in db

- src/fractl/component.cljc
- src/fractl/evaluator.cljc
- src/fractl/global_state.cljc
- src/fractl/lang.cljc
- src/fractl/model/fractl/kernel/identity.cljc
- src/fractl/model/fractl/kernel/lang.cljc
- src/fractl/model/fractl/kernel/rbac.cljc
- src/fractl/model/fractl/kernel/store.cljc
- src/fractl/model/model.cljc
- src/fractl/store/util.cljc
- test/fractl/test/basic.cljc
No separate schema-version is needed. (This is a follow-up on https://github.com/fractl-io/fractl/issues/1162).
> Use model-version as db-schema-version.

- src/fractl/evaluator.cljc
- src/fractl/store.cljc
- src/fractl/store/alasql_internal.cljs
- src/fractl/store/db_common.cljc
- src/fractl/store/jdbc_internal.clj
- test/fractl/test/fixes02.cljc
> Issue 1062 - fix rollback on transactions for exceptions consumed by eval-with-logs

- fractl/fractl/kernel/identity.fractl
- src/fractl/http.clj
- src/fractl/model/fractl/kernel/identity.cljc
- src/fractl/model/fractl/kernel/lang.cljc
- src/fractl/model/fractl/kernel/rbac.cljc
- src/fractl/model/fractl/kernel/store.cljc
- src/fractl/util/http.cljc
Reverts fractl-io/fractl#1169
As this PR seems to break RBAC, we will revert this for now and later merge it in another PR.
> Revert "Ensure tokens revoked from Cognito aren't used to interact with Fractl"

- src/fractl/compiler.cljc
- test/fractl/test/fixes03.cljc
> Fix pattern pre-processing for multi-parent relationships

- src/fractl/component.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/util/http.cljc
> prevent loops in cascading-delete.

- fractl/fractl/kernel/identity.fractl
- src/fractl/auth/cognito.clj
- src/fractl/auth/core.cljc
- src/fractl/model/fractl/kernel/identity.cljc
- src/fractl/model/fractl/kernel/lang.cljc
- src/fractl/model/fractl/kernel/rbac.cljc
- src/fractl/resolver/authentication.cljc
Changes:
* Store AppId user in auth backend
* `get-user` endpoint also returns :AppId
> `get-user` endpoint should return ID of associated `:User` entity instance

- src/fractl/gpt/core.cljc
- src/fractl/http.clj
Changes:
* Update structure of API requests to _ai/
* Support for tunings changes made via client for OpenAI tunings like frequency_penalty, etc.
* System prompt can be custom for different operation not just generation of an app.
> Update API to handle custom system messages and tuning parameters

- src/fractl/auth/cognito.clj
Since, we store OpenAI key in cognito so, it can be retrieved and changed from Design Studio.
We will need to store Fine-tuned models here too so that user can switch Fine-tuned model via Design Studio depending on their use-case.
> Add information for fine-tuned-model in cognito

- src/fractl/component.cljc
- src/fractl/lang/syntax.cljc
- src/fractl/paths.cljc
- test/fractl/test/features01.cljc
allow empty attributes in query syntax
> fix between relationship names lookup.

- .github/workflows/fractl-clj.yml
- src/fractl/lang/syntax.cljc
- test/fractl/test/features01.cljc
- test/fractl/test/features02.cljc
- test/fractl/test/fixes03.cljc
- remove unsupported :-> tag
- add support for :purge and :*
> update syntax support for :delete.

- .github/workflows/fractl-clj.yml
- src/fractl/compiler.cljc
- src/fractl/component.cljc
- src/fractl/env.cljc
- src/fractl/evaluator.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/evaluator/state.cljc
- src/fractl/lang.cljc
- src/fractl/lang/internal.cljc
- src/fractl/paths.cljc
- test/fractl/test/features02.cljc
- test/fractl/test/features04.cljc
See https://github.com/fractl-io/fractl/issues/713#issuecomment-1920986147 for current implementation details.
> Issue 713 expr with relationships

- src/fractl/compiler.cljc
- src/fractl/component.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/http.clj
- src/fractl/lang.cljc
- src/fractl/lang/internal.cljc
- src/fractl/lang/syntax.cljc
- src/fractl/paths.cljc
- src/fractl/paths/internal.cljc
- src/fractl/util/http.cljc
- test/fractl/test/features02.cljc
- test/fractl/test/features03.cljc
- test/fractl/test/features04.cljc
- test/fractl/test/rbac.cljc
- test/fractl/test/resolver.cljc
> Issue 1211 contains syntax support

- .github/workflows/fractl-clj.yml
> Fix Windows CI

- src/fractl/evaluator/root.cljc
- src/fractl/resolver/core.cljc
- test/fractl/test/resolver.cljc
> relationship context support for resolvers

- project.clj
- src/fractl/auth/oauth2.cljc
- test/fractl/test/auth.cljc
- test/sample/github/README.md
- test/sample/github/config.edn
- test/sample/github/github.fractl
- test/sample/github/model.fractl
> Issue 1226 auth persistent conns

- src/fractl/compiler.cljc
- test/fractl/test/fixes02.cljc
> Issue 1234 edn empty vector

- project.clj
- src/fractl/resolver/core.cljc
- src/fractl/subs.cljc
- src/fractl/subs/internal.cljc
- src/fractl/subs/kafka.cljc
- test/fractl/test/resolver.cljc
> Issue 1227 push notifications

- src/fractl/subs.cljc
- src/fractl/subs/internal.cljc
- src/fractl/subs/kafka.cljc
- src/fractl/subs/mem.cljc
- test/fractl/test/resolver.cljc
> transformers for change-notifications

- src/fractl/component.cljc
> fix parsing of unqualified entity-name

- src/fractl/compiler/rule.cljc
- src/fractl/component.cljc
- src/fractl/env.cljc
- src/fractl/evaluator.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/lang.cljc
- src/fractl/lang/internal.cljc
- src/fractl/lang/name_util.cljc
- src/fractl/lang/raw.cljc
- src/fractl/lang/tools/loader.cljc
- src/fractl/rule.cljc
- src/fractl/subs.cljc
- src/fractl/subs/internal.cljc
- src/fractl/util/seq.cljc
- test/fractl/test/features05.cljc
Implements the basic rule-construct as defined in #1252.
fixes #1252.
> Issue 1252 rules

- src/fractl/component.cljc
- test/fractl/test/features04.cljc
> docstring support

- CHANGELOG.md
- project.clj
> Revert "Release version 0.5"

- src/fractl/lang/tools/build.clj
- src/fractl/lang/tools/loader.cljc
- src/fractl/lang/tools/util.cljc
- test/sample/dependencies/banking/.gitignore
- test/sample/dependencies/banklib/banklib/core.fractl
- test/sample/dependencies/banklib/model.fractl
- test/sample/dependencies/billing/billing/core.fractl
- test/sample/dependencies/billing/model.fractl
Local and github dependencies can be specified under the `:dependencies` key. Please see `test/sample/dependencies/billing` for usage example.
> Simpler dependency specification in model.fractl

- example/clickhouse/logs.fractl
- src/fractl/compiler.cljc
- src/fractl/component.cljc
- src/fractl/resolver/click_house.clj
- src/fractl/store/db_common.cljc
- src/fractl/store/sql.cljc
- test/fractl/test/features05.cljc
> Issue 1300 - joins

- example/clickhouse/logs.fractl
- src/fractl/compiler.cljc
- src/fractl/component.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/lang.cljc
- src/fractl/lang/name_util.cljc
- src/fractl/lang/tools/loader.cljc
- src/fractl/resolver/click_house.clj
- src/fractl/store/db_common.cljc
- src/fractl/store/sql.cljc
- src/fractl/store/util.cljc
- test/fractl/test/features05.cljc
> Issue 1301 - views

- src/fractl/lang.cljc
- src/fractl/lang/tools/build.clj
- src/fractl/store/sql.cljc
> handle attribute-names with sub-models.

- src/fractl/auth/okta.clj
- src/fractl/http.clj
- cookie configurable domain
- use :username for okta
> Okta username & cookie fixes

- src/fractl/lang/tools/repl.clj
> drop table only on schema-change

- src/fractl/lang/raw.cljc
- src/fractl/lang/tools/build.clj
- src/fractl/lang/tools/loader.cljc
Publish component create/delete.
> Support lein-deps format in model dependencies.

- src/fractl/component.cljc
- src/fractl/lang.cljc
- src/fractl/lang/pub_schema.clj
- src/fractl/lang/tools/build.clj
Add app-uuid in pub-schema event.
> Support new resolver construct in fractl-lang.

- src/fractl/util/logger.cljc
- src/fractl/util/runtime.clj
> Convert logging functions to macros

- src/fractl/compiler.cljc
- src/fractl/lang/internal.cljc
- src/fractl/lang/syntax.cljc
- test/fractl/test/features05.cljc
> documentation support for patterns

- src/fractl/component.cljc
> force normal map-attributes to proper instances where required

- src/fractl/graphql/core.clj
This will allow users to use an existing GraphQL schema file (particularly, useful when there's some error in the auto-generated schema, they can modify the generated saved schema to fix bugs and then specify the path to the updated schema).
> Allow GraphQL schema path specification

- src/fractl/component.cljc
- src/fractl/lang/raw.cljc
- test/fractl/test/features05.cljc
Api for fetching and updating component specifications.
> Component api

- bin/fractl
- project.clj
- src/fractl/inference/service/lib/agent.clj
- src/fractl/inference/service/logic.clj
- src/fractl/lang.cljc
* support tools, docs and prompt-generation in inference construct
* remove SNAPSHOT from fractl-version. (this causes issues with lein)
> Inference syntax changes

- src/fractl/lang/tools/build.clj
> Simplified ns name generation

- src/fractl/compiler.cljc
- src/fractl/compiler/context.cljc
- src/fractl/env.cljc
- src/fractl/evaluator/root.cljc
- src/fractl/lang/internal.cljc
- src/fractl/lang/syntax.cljc
- src/fractl/util/seq.cljc
- test/fractl/test/features05.cljc
Support rethrow of errors from patterns. E.g:
```clojure
{:Twist/AllocateCapcity {}
:throw
[:not-found {:Twist/AllocationFailure {:Message "data not found"}}
:error {:Twist/AllocationFailure {:Message (str "internal error: " :Error)}}]
;; ...
}
```
> Throw pattern

- example/llm/planner/model.fractl
- example/llm/planner/planner/core.fractl
- src/fractl/inference/provider.clj
- src/fractl/inference/service/model.clj
- src/fractl/inference/service/tools.clj
- src/fractl/util.cljc
Planner as agent composition example.
> Use entities as tools for planner

- src/fractl/graphql/core.clj
- src/fractl/graphql/generator.clj
- src/fractl/graphql/resolvers.clj
Added support for basic translation of GraphQL filters to Fractl Patterns to improve query performance.
> Added support for translation of GraphQL filters to Fractl Patterns

- src/agentlang/evaluator/root.cljc
- src/agentlang/http.clj
- test/agentlang/test/fixes04.cljc
check type of post request - it should match the endpoint.
fixes #1494
> fix result parsing in try-block.

- src/agentlang/store/db_common.cljc
> use truncated pk, fk and index names

- example/agents/selfservice/resolvers/ticket/ticket/core.al
- example/agents/selfservice/selfservice/core.al
- src/agentlang/inference/service/logic.clj
- src/agentlang/lang/tools/loader.cljc
more directions related to aliases for planner
> load references in script.

- README.md
- example/agents/joke/joke/core.al
- example/agents/planner/planner/core.al
- src/agentlang/inference.cljc
- src/agentlang/inference/service/logic.clj
- src/agentlang/inference/service/model.cljc
- src/agentlang/inference/service/planner.clj
- src/agentlang/lang.cljc
1. User control over multiple chat-sessions.
2. Arbitrary event input for planner.
> Agent enhancements

- src/agentlang/lang/kernel.cljc
> fix email validation

- src/agentlang/compiler.cljc
- src/agentlang/env.cljc
- src/agentlang/evaluator/root.cljc
- test/agentlang/test/fixes04.cljc
> fix alias-ref with dynamic type

- src/agentlang/auth/core.cljc
> on-user-login is an internal event

- src/agentlang/compiler.cljc
- test/agentlang/test/fixes04.cljc
> Preprocess try-body

- src/agentlang/component.cljc
- test/agentlang/test/fixes04.cljc
> apply require preprocessor on listof-data

- src/agentlang/http.clj
https://github.com/agentlang-ai/agentlang/issues/1470
> auth config option to disable local user sessions

- src/agentlang/global_state.cljc
- src/agentlang/lang.cljc
- src/agentlang/util/runtime.clj
- test/agentlang/test/migrations.clj
Fixes duplicate component load issue in design-studio.
> remove old component on reload

- src/agentlang/http.clj
> retrun 415 on unsupported content-type

- example/agents/ecommerce-review-analysis/ecommerce_review_analysis/core.al
- src/agentlang/inference/service/model.cljc
> Transaction isolation for internal agent dataflows

- src/agentlang/evaluator/suspend.cljc
- src/agentlang/lang/tools/schema/model.cljc
> support vectors of connection-types

- src/agentlang/inference/service/model.cljc
* Only import planner for clj
* Fix logger issues
* Fix slurp calls which doesn't work for cljs
> Fix cljs compile issues

- src/agentlang/connections/client.clj
- src/agentlang/util/http.cljc
- src/agentlang/util/runtime.clj
support urls with spaces in integrations lookup
> fix url-encoding issue

- src/agentlang/util.cljc
> cljs should only log errors

- .gitignore
- resources/scripts/maybe-download-vec0.sh
- scripts/maybe-download-vec0.sh
- src/agentlang/inference/embeddings/core.clj
- src/agentlang/inference/embeddings/internal/common.clj
- src/agentlang/inference/embeddings/internal/pgvector.clj
- src/agentlang/inference/embeddings/internal/sqlitevector.clj
- src/agentlang/inference/embeddings/pgvector.clj
- src/agentlang/inference/embeddings/sqlitevector.clj
- src/agentlang/util.cljc
Uses [sqlite-vec](https://github.com/asg017/sqlite-vec)
> `sqlite-vec` implementation for vector search

- src/agentlang/inference/provider/anthropic.clj
> Add cache support for anthropic

- src/agentlang/component.cljc
- src/agentlang/lang/datetime.cljc
- src/agentlang/lang/kernel.cljc
- test/agentlang/test/fixes01.cljc
> fix datetime try-parse, add date-time test

- src/agentlang/http.clj
fixes #1727 
Supports params like:
* `?X=20&Y=[:> 30]`
* `?S="hello world"`
* `?S=[:like "hello%"]`
Expressions like `[:> 30]` and `[:like "hello%"]` may have to be url-encoded.
> filter by query-params

- src/agentlang/component.cljc
- src/agentlang/interpreter.cljc
- test/agentlang/test/features01.cljc
> unique-in support

- src/agentlang/component.cljc
- src/agentlang/lang/internal.cljc
- src/agentlang/util.cljc
- src/agentlang/util/http.cljc
- test/agentlang/test/fixes01.cljc
- test/agentlang/test/util.cljc
> treat comma as reserved character in ids

- src/agentlang/http.clj
- src/agentlang/lang.cljc
- src/agentlang/lang/name_util.cljc
- src/agentlang/lang/raw.cljc
- test/agentlang/test/timer.cljc
> schedule construct

- src/agentlang/inference/service/model.cljc
- src/agentlang/interpreter.cljc
evaluate env-vars in fn body for call
> simple check for cross-platform chat-sessions.

- src/agentlang/lang.cljc
- src/agentlang/lang/internal.cljc
- test/agentlang/test/basic.cljc
there are no such restrictions required in attribute-names.
> allow reserved-words as attribute-names

- src/agentlang/component.cljc
- src/agentlang/interpreter.cljc
- test/sample/simple.al
if the entity does not have compound attributes.
> skip compound-attribute loop - 

- CHANGELOG.md
- README.md
- project.clj
Additionally, fix README for CI links and update CHANGELOG.md.
> Release v0.7.0 with new features and updates.
