src/fractl/http.clj
Added a message "The HTTP server is listening on port XXXX" when doing `fractl run`.
Also, I noticed that you default to port 8080 if no config is provided, but there was a situation when you did have a config, but there was no :port setting in this config, then the `run-server` function fell back on http-kit library default (8090). I think you want your 8080 default always apply if no :port is given. So I fixed that too.
Only 3 lines actually changed. All others are only indented because of the additional (let []).
=> Fix default port and add a server message

fractl/fractl/kernel/identity.fractl, src/fractl/http.clj, src/fractl/model/fractl/kernel/identity.cljc, src/fractl/model/fractl/kernel/lang.cljc, src/fractl/model/fractl/kernel/rbac.cljc, src/fractl/model/fractl/kernel/store.cljc, src/fractl/util/http.cljc
Keep track of UserSessions and safe guard against Users who have logged out from Design Studio yet, use the JWT token via HTTP requests.
=> Ensure tokens revoked from Cognito aren't used to interact with Fractl

src/fractl/gpt/core.cljc
Sometimes chat-response which we might send it over to _ai/ might be complicated nesting with other additional information like texts and other data-structures. It shouldn't be Fractl that should handle such, so, it must be the responsibility of client to only send the proper fractl code to Fractl side of things.
=> Don't handle complicated nesting on chat-response

src/fractl/lang/tools/loader.cljc
This PR fixes the corner-case when the loader fails for code ending with comment on he last line of the file:
```clojure
; some comment (last line in the file)
```
with the following stack trace:
```
Exception in thread "main" java.lang.RuntimeException: EOF while reading
at clojure.lang.Util.runtimeException(Util.java:221)
at clojure.lang.LispReader.readDelimitedList(LispReader.java:1403)
at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1243)
at clojure.lang.LispReader.read(LispReader.java:285)
at clojure.lang.LispReader.read(LispReader.java:216)
at clojure.lang.LispReader.read(LispReader.java:205)
at clojure.lang.RT.readString(RT.java:1879)
at clojure.lang.RT.readString(RT.java:1874)
at clojure.core$read_string.invokeStatic(core.clj:3803)
at …
```
=> fix loading when last line is commented (with semicolon)

src/fractl/compiler.cljc
The pre-processing step was missing for nested between relationships. This is added in this PR.
=> Pre-process embedded between spec

src/fractl/lang/internal.cljc, test/fractl/test/features04.cljc
This will be required for automated schema imports for external systems like SFDC.
=> Allow underscores in user-defined names

src/fractl/lang/tools/loader.cljc, src/fractl/model/fractl/kernel/identity.cljc
When a component's entities/relationships/dataflows are loaded one by one, if any of them is fails (is "corrupted"), we check it using try-catch block. To indicate it's failed so that Design Studio can render the erroneous entity, we create a dummy entity for that with its name and type (entity/relationship/so on) and mark it as corrupted via meta so that Design Studio doesn't treat it as a regular entity.
```
(defn get-corrupted-entity-form [entity-name t]
`(~'entity
~entity-name
{:meta {:corrupt true, :type ~t}}))
```
Also check https://github.com/fractl-io/design-studio/pull/214
=> Loader step wise

src/fractl/component.cljc, src/fractl/evaluator/root.cljc, src/fractl/lang/internal.cljc, test/fractl/test/resolver.cljc
Handle cascading deletions when parent or children (or both) are managed by resolvers.
=> Parent-child relationships in resolvers

src/fractl/http.clj
Previously, the workflow was this: get the ID token from Cognito Google Auth UI directly and then call `/_authcallback` endpoint manually from frontend to optionally execute post signup. The limitation was, it didn't give us refresh token.
I refactored it such that:
- Google Auth directly leads us to /_authcallback with a 'code'. 
- We call a REST endpoint of Cognito to get `id_token` and `refresh_token` for that code
- if successful, redirect the user to a provided (in the request) or default (in env var) redirect URL, usually the application frontend
=> Refactor auth callback

src/fractl/compiler.cljc, src/fractl/compiler/internal.cljc, src/fractl/lang/internal.cljc, test/fractl/test/features02.cljc, test/fractl/test/features03.cljc, test/fractl/test/fixes02.cljc
fixes #1223 
Also includes:
1. a bug fix in lookup based on `:where` query alias.
2. test for a copilot use-case
=> Issue 1223 - path query syntax

src/fractl/component.cljc, src/fractl/http.clj
fixes #1236 
1. `GET /meta/<component-name>` will return user-defined spec for entities, records and relationships.
2. `GET /meta` will return a list of all component namers.
=> Issue 1236 meta fix

src/fractl/evaluator.cljc, src/fractl/subs/kafka.cljc, src/java/fractl/subs/HandleRebalance.java, test/fractl/test/resolver.cljc
fine-grained control over commits.
handler for partition-rebalancing.
make use of consumer's internal mechanism for closing connection.
fixes #1241
=> update kafka-consumer for distributed-environment.

project.clj, src/fractl/lang/tools/build.clj, src/fractl/subs.cljc
Users can define and add their own pub-sub clients to the Fractl runtime.
=> Support for registering user-defined subscription clients

src/fractl/compiler.cljc, src/fractl/component.cljc, src/fractl/env.cljc, src/fractl/evaluator.cljc, src/fractl/evaluator/root.cljc, src/fractl/http.clj, src/fractl/util/http.cljc, test/fractl/test/features04.cljc, test/sample/simple.fractl
Note: This initial version of the debugger maintains sessions in memory - objective of the PR is to get the public interface reviewed.
Start a debugging session:
```
POST /debug
{"EventName": {"Attribute": "Value"}}
```
This will return a debug-session-id. To step:
```
PUT /debug/step/<id>
```
The response will be in the format `[session-id result-map]`, where `result-map` will contain the keys - 
`:status` - the status of evaluating the next pattern - `:ok` or `:error`.
`:result` - the value of the pattern 
`:env` - the local value bindings of the evaluator
`:pattern` - the original pattern that was evaluated
To continue from the current to the last step:
```
PUT /debug/continue/id
```
The `continue` API will return the value of the last pattern that was evaluated.
To cancel a …
=> Dataflow debugger with HTTP API support

src/fractl/resolver/click_house.clj
Escaped string values like `"[\"abc\": 123]"` turn into `"["abc": 123]"` when inserting them into Clickhouse. It causes parsing errors when retrieving it.
The solution is to turn it into `"[\\\"abc\\\": 123]"` before inserting.
=> fix escape quoted strings in clickhouse

src/fractl/compiler/validation.cljc, src/fractl/lang/name_util.cljc
Do not enforce schema check on inferred-event pattern.
=> Handle inference in the script loader.

fractl/fractl/kernel/lang.fractl, src/fractl/component.cljc, src/fractl/evaluator.cljc, src/fractl/model/fractl/kernel/identity.cljc, src/fractl/model/fractl/kernel/lang.cljc, src/fractl/model/fractl/kernel/rbac.cljc, src/fractl/util/core.clj
Example:
```clojure
; model.fractl
{:name "blog"
:fractl-version "0.5.1"
:components [:Blog.Core]
:config-entity :Blog.Core/Config}
```
```clojure
; config.edn
{:service {:port 8000}
:store {:type :h2
:dbname "./data/blog"}
:Blog.Core/Config {:RemoteHost "https://remote.blog.com"}}
```
Config entity definition:
```clojure
(entity
:Blog.Core/Config
{:meta {:inherits :Fractl.Kernel.Lang/Config}
:RemoteHost :String})
```
Accessing the config instance from a dataflow pattern:
```clojure
{:Blog.Core/Config? {} :as [:config]}
{:Remote/Blog {:Id? "123" :Host :config.RemoteHost}}
```
Accessing config instance from clojure:
```
(fractl.evaluator/fetch-model-config-instance "blog") 
```
=> Support for model-specific config entities

src/fractl/inference.cljc
If review-mode is set in the event-context, return the unevaluated patterns. E.g:
```clojure
> {:Acme/OnNewLead {:IncomingLead {:Salesforce/Lead {:Id "00001", :Email: "aaa@sss.com"}} :EventContext {:inference-review-mode true}}} ; return patterns unevaluated
> {:Acme/OnNewLead {:IncomingLead {:Salesforce/Lead {:Id "00001", :Email: "aaa@sss.com"}}}} ; return result of evaluating the patterns
```
=> Review-mode support for inference events.

src/fractl/evaluator.cljc, src/fractl/util/core.clj
1. fallback for fetching model-config-instance, read from app-config if not-found in the db.
2. support for multiple init-fns - executed in the order they were added to the queue.
=> Model config fallback

src/fractl/lang.cljc, src/fractl/util/http.cljc
so any pending resolver-type registration can happen.
=> Run the require namespaces before init,

.github/workflows/publish-new-release.yml
This update amends the automated release workflow by adding steps to calculate the SHA256 checksums for both the JAR and the standalone Uberjar. These checksums are then included in the release notes for the update. This will provide users the ability to verify the integrity of downloaded files for added security.
=> Add SHA256 checksum calculation to release workflow

bin/fractl
Updated the FRACTL_VERSION from "0.5.1" to "0.5.2" and modified the corresponding FRACTL_CHECKSUM to match the new version. This update ensures the correct version is exported during processes.
Fixes #1358
=> Update FRACTL version and checksum

src/fractl/component.cljc, src/fractl/graphql/generator.clj, src/fractl/graphql/resolvers.clj, test/fractl/test/graphql.cljc
Improved automatic GraphQL resolver and schema code generation to support complex filters with arbitrary depth.
Supported comparison operators:
- eq (equal)
- ne (not equal)
- gt (greater than)
- gte (greater than or equal)
- lt (less than)
- lte (less than or equal)
- in (value in list)
- contains (string contains)
- startsWith (string starts with)
- endsWith (string ends with)
- between (value between two numbers)
Logical operators:
- AND
- OR
- NOT
Example Query:
```graphql
query getMultiConditionFilteredHeros($filter: HeroFilter) {
Hero (filter: $filter) {
Id
Name
HomePlanet
Age
ForceSensitive
}
}
Variables:
{
"filter": {
"and": [
{
"or": [
{ "Age": { "gte": 30, "lt": 100 } },
{
"and": [
{ "Age": { "gte": 20, "lt": 30 } },
{ "ForceSensitive": true }
]
}
]
},
{ "not": { "HomePlanet": { …
```
=> GraphQL resolver and schema generation to support filters, offset, limit

src/fractl/core.clj
nREPL uses a default port of 7888. So, reverting to it. To allow flexibility for change, the config specification could be used:
```
:nrepl {:port 7000
:bind "127.0.0.1"}
```
=> nREPL fix and config options

src/fractl/component.cljc, src/fractl/graphql/generator.clj, src/fractl/graphql/resolvers.clj, src/fractl/http.clj, test/fractl/test/graphql.cljc
Please see unit tests for examples of deeply nested queries and mutations. 
PR also fixes the bug affecting the absence of between relationship filter objects.
=> Support arbitrary depth of records in graphql queries and mutations, Filter Generation Fix

src/fractl/component.cljc, test/fractl/test/errors.cljc
This is required to maintain compatibility with the dataflow compilation process and runtime internals, where all names as treated as a vector of keywords, as in `[:ComponentName :EntityName]`.
=> Parse record-name to parts in a direct call to make-instance

src/fractl/util.cljc
Report the missing env-var in the `$` reader-exception.
=> report envvar missing error

src/fractl/lang/tools/build.clj
- Change `:use` to `:require` (and `:only` to `:refer`) in built models
- Change modelmain.clj to modelmain.cljc for ClojureScript compatibility
=> change :use to :refer when building model

project.clj, src/agentlang/core.clj, src/agentlang/http.clj, src/agentlang/lang/tools/nrepl/core.clj, src/agentlang/util/http.cljc
PR supports accessing nREPL functionality over HTTP endpoint `/nrepl` - authentication will be applicable same as other endpoints. nREPL endpoint isn't available by default and can be enabled through config:
```
{:service {:port 8080}
:nrepl {:enabled true}}
```
=> added nrepl endpoint with auth support

src/agentlang/component.cljc, test/agentlang/test/features05.cljc
fixes agentlang.test.features05/views-on-contains for postgres
=> exact type for parent attribute is needed for postgres `=` operator

src/agentlang/evaluator.cljc, src/agentlang/http.clj
Changes:
* Add logger support for nREPL request and evaluation
* Update response from nREPL simplflying it and removing env keys with tags which cljs reader cannot read
=> Add logger in nREPL and send cleaner response

example/agents/selfservice/model.al, src/agentlang/lang/tools/loader.cljc
`{:model <model-name>}` is no longer mandatory in `:git` and `:fs` dependencies.
=> make git model-name optional

project.clj, src/agentlang/component.cljc, src/agentlang/core.clj, src/agentlang/lang/tools/build.clj, src/agentlang/lang/tools/loader.cljc, src/agentlang/store/db_common.cljc, src/agentlang/store/util.cljc, src/agentlang/util/runtime.clj, test/agentlang/test/migrations.clj, test/sample/migrations/11-auto-migrate-entities/factory.al, test/sample/migrations/11-auto-migrate-entities/model.al, test/sample/migrations/11-auto-migrate-entities/office.al, test/sample/migrations/11-auto-migrate-entities/old/factory/factory.al, test/sample/migrations/11-auto-migrate-entities/old/factory/model.al, test/sample/migrations/11-auto-migrate-entities/old/factory/office.al, test/sample/migrations/11-auto-migrate-entities/old/factory/retail.al, test/sample/migrations/11-auto-migrate-entities/retail.al, test/sample/migrations/12-auto-migrate-with-dependencies/factory/factory.al, test/sample/migrations/12-auto-migrate-with-dependencies/factory/model.al, test/sample/migrations/12-auto-migrate-with-dependencies/factory/old/factory/factory.al, test/sample/migrations/12-auto-migrate-with-dependencies/factory/old/factory/model.al, test/sample/migrations/12-auto-migrate-with-dependencies/office/model.al, test/sample/migrations/12-auto-migrate-with-dependencies/office/office.al, test/sample/migrations/12-auto-migrate-with-dependencies/office/old/office/model.al, test/sample/migrations/12-auto-migrate-with-dependencies/office/old/office/office.al
Enhancements:
- user can now specify either a local path or git for migration flow to fetch old schema
- all entities are automatically migrated unless explicitly specified in config.edn `:no-auto-migration`
Example:
```
:no-auto-migration #{:Factory.Core/Customer
:Agentlang.Kernel.Lang
:SomeDependencyModel} 
```
One can specify either an entity or a component or entire (dependency) model to exclude.
=> Migration enhancements: renaming tables & git support

src/agentlang/component.cljc, src/agentlang/core.clj, src/agentlang/util/http.cljc
- Previous syntax was: `agent --doc model-name`. Current syntax is: `agent doc model-name` or just `agent doc` in the model.
- API path fix
=> Improvements in docs CLI syntax

example/agents/expense/expense/workflow.al, src/agentlang/inference/service/model.cljc, src/agentlang/inference/service/tools.clj, src/agentlang/lang.cljc, src/agentlang/lang/raw.cljc
No explicit `:Input` attribute required for agents. The input-event will be auto-generated by the runtime.
=> automatic input events
